pages:
 image: node:latest
 stage: deploy
 script:
  - export NODE_OPTIONS=--openssl-legacy-provider
  - yarn install
  - yarn build --mode development
  - rm -rf public
  - mkdir public
  - cp -r dist/* public
  - cp public/index.html public/404.html
 artifacts:
  expire_in: 1 day
  paths:
  - public
 only:
  - main
